name: Validacion de archivos y pulls 

on:
  push:
      branches:
        - main

  pull_request:
       branches:
          - main

jobs:
  validar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: verificar index.html
        run: test -f frontend/index.html

      - name: Verificar css
        run: test -f frontend/style.css

      - name: Verificar PY
        run: test -f backend/app.py

      - name: Verificar README
        run: test -f README.md  

        
