name: Comprobacion de push

on:
  push:
    branches:
      - main

jobs:
  validar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: verificar index.html
        run: test -f index.html

      - name: Verificar css
        run: test -f css/style.css

      - name: Verificar JS
        run: test -f js/script.js

        
